import type { BookingLanguage } from '../shared/contracts'

export const telegramCopy = {
  en: {
    welcome: 'Care for your car, scheduled precisely.', lead: 'Live availability, server-calculated estimates and your VELORA bookings in one place.', services: 'Services', book: 'Book', bookings: 'Bookings', profile: 'Profile', chooseServices: 'Choose services', continue: 'Continue', vehicle: 'Vehicle', savedVehicle: 'Saved vehicle', newVehicle: 'New vehicle', makeModel: 'Make and model', category: 'Vehicle type', condition: 'Current condition', date: 'Preferred date', available: 'Available starts', noSlots: 'No suitable start times on this date.', details: 'Contact details', name: 'Full name', phone: 'Phone', email: 'Email', notes: 'Additional message', consent: 'I agree to the booking terms and privacy notice.', overnight: 'I understand that this service continues into the next working day.', review: 'Review request', submit: 'Send booking request', total: 'Server estimate', duration: 'Estimated work time', pending: 'The request is pending studio confirmation.', retry: 'Try again', telegramOnly: 'Open this page from the VELORA Telegram bot to sign in securely.', openWebsite: 'Open full website', upcoming: 'Upcoming', history: 'History', noBookings: 'No linked bookings yet.', garage: 'My cars', addCar: 'Add car', edit: 'Edit', save: 'Save', registration: 'Registration (optional)', linkedAfter: 'Cars can be saved after your first booking links your customer profile.', notifications: 'Telegram notifications', enableNotifications: 'Enable updates', notificationsOn: 'Updates enabled', error: 'Something went wrong. Please try again.', conflict: 'That time was just taken. Choose another start.', back: 'Back', from: 'from', minutes: 'min', language: 'Language', selected: 'selected', success: 'Request saved', reference: 'Reference', close: 'Done', loading: 'Loading VELORA…', authError: 'Secure Telegram sign-in failed. Close the Mini App and open it again.',
  },
  lv: {
    welcome: 'Precīza auto kopšanas vizīte.', lead: 'Brīvie laiki, serverī aprēķināta tāme un jūsu VELORA vizītes vienuviet.', services: 'Pakalpojumi', book: 'Pieteikties', bookings: 'Vizītes', profile: 'Profils', chooseServices: 'Izvēlieties pakalpojumus', continue: 'Turpināt', vehicle: 'Auto', savedVehicle: 'Saglabāts auto', newVehicle: 'Jauns auto', makeModel: 'Marka un modelis', category: 'Auto tips', condition: 'Pašreizējais stāvoklis', date: 'Vēlamais datums', available: 'Pieejamie sākuma laiki', noSlots: 'Šajā datumā nav piemērotu laiku.', details: 'Kontaktinformācija', name: 'Vārds, uzvārds', phone: 'Tālrunis', email: 'E-pasts', notes: 'Papildu ziņa', consent: 'Piekrītu rezervācijas noteikumiem un privātuma paziņojumam.', overnight: 'Saprotu, ka darbs turpināsies nākamajā darba dienā.', review: 'Pārbaudiet pieteikumu', submit: 'Nosūtīt pieteikumu', total: 'Servera tāme', duration: 'Aptuvenais darba laiks', pending: 'Pieteikums gaida studijas apstiprinājumu.', retry: 'Mēģināt vēlreiz', telegramOnly: 'Atveriet šo lapu no VELORA Telegram bota drošai autorizācijai.', openWebsite: 'Atvērt pilno vietni', upcoming: 'Gaidāmās', history: 'Vēsture', noBookings: 'Piesaistītu vizīšu vēl nav.', garage: 'Mani auto', addCar: 'Pievienot auto', edit: 'Rediģēt', save: 'Saglabāt', registration: 'Reģistrācijas numurs (nav obligāts)', linkedAfter: 'Auto var saglabāt pēc pirmās vizītes, kad profils ir piesaistīts.', notifications: 'Telegram paziņojumi', enableNotifications: 'Ieslēgt ziņas', notificationsOn: 'Ziņas ieslēgtas', error: 'Radās kļūda. Mēģiniet vēlreiz.', conflict: 'Šis laiks tikko tika aizņemts. Izvēlieties citu.', back: 'Atpakaļ', from: 'no', minutes: 'min', language: 'Valoda', selected: 'izvēlēti', success: 'Pieteikums saglabāts', reference: 'Atsauce', close: 'Gatavs', loading: 'Ielādē VELORA…', authError: 'Droša Telegram autorizācija neizdevās. Aizveriet Mini App un atveriet vēlreiz.',
  },
  ru: {
    welcome: 'Точный уход — в удобное время.', lead: 'Свободные даты, расчёт на сервере и ваши записи VELORA в одном месте.', services: 'Услуги', book: 'Записаться', bookings: 'Записи', profile: 'Профиль', chooseServices: 'Выберите услуги', continue: 'Продолжить', vehicle: 'Автомобиль', savedVehicle: 'Сохранённый автомобиль', newVehicle: 'Новый автомобиль', makeModel: 'Марка и модель', category: 'Тип автомобиля', condition: 'Текущее состояние', date: 'Желаемая дата', available: 'Доступное время начала', noSlots: 'На эту дату подходящего времени нет.', details: 'Контактные данные', name: 'Имя и фамилия', phone: 'Телефон', email: 'Email', notes: 'Дополнительное сообщение', consent: 'Я согласен с условиями записи и уведомлением о конфиденциальности.', overnight: 'Я понимаю, что работа продолжится в следующий рабочий день.', review: 'Проверьте заявку', submit: 'Отправить заявку', total: 'Расчёт сервера', duration: 'Примерное время работы', pending: 'Заявка ожидает подтверждения студии.', retry: 'Повторить', telegramOnly: 'Откройте эту страницу из Telegram-бота VELORA для безопасного входа.', openWebsite: 'Открыть полный сайт', upcoming: 'Предстоящие', history: 'История', noBookings: 'Связанных записей пока нет.', garage: 'Мои автомобили', addCar: 'Добавить автомобиль', edit: 'Изменить', save: 'Сохранить', registration: 'Госномер (необязательно)', linkedAfter: 'Автомобиль можно сохранить после первой записи, когда профиль будет связан.', notifications: 'Уведомления Telegram', enableNotifications: 'Включить уведомления', notificationsOn: 'Уведомления включены', error: 'Что-то пошло не так. Повторите попытку.', conflict: 'Это время только что заняли. Выберите другое.', back: 'Назад', from: 'от', minutes: 'мин', language: 'Язык', selected: 'выбрано', success: 'Заявка сохранена', reference: 'Номер', close: 'Готово', loading: 'Загрузка VELORA…', authError: 'Не удалось выполнить безопасный вход через Telegram. Закройте Mini App и откройте снова.',
  },
} satisfies Record<BookingLanguage, Record<string, string>>
