import { LoaderCircle, Save, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { loadSettings, saveSettings, type AdminSettings } from '../api'
import type { BusinessHours, SchedulingSettings, Service, ServicePackage } from '../types'

const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

export function SettingsPage() {
  const [data, setData] = useState<AdminSettings | null>(null)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const [exceptionDate, setExceptionDate] = useState('')
  const [exceptionClosed, setExceptionClosed] = useState(true)
  const [exceptionOpen, setExceptionOpen] = useState('10:00')
  const [exceptionClose, setExceptionClose] = useState('20:00')
  const [note, setNote] = useState('')

  useEffect(() => { loadSettings().then(setData).catch(() => setError('Settings could not be loaded.')) }, [])
  const run = async (input: Record<string, unknown>) => {
    setSaving(true); setError('')
    try { setData(await saveSettings(input)) } catch { setError('The setting could not be saved.') } finally { setSaving(false) }
  }
  const updateLocalHours = (weekday: number, patch: Partial<BusinessHours>) => setData((current) => current ? { ...current, businessHours: current.businessHours.map((row) => row.weekday === weekday ? { ...row, ...patch } : row) } : current)
  const updateLocalService = (id: string, patch: Partial<Service>) => setData((current) => current ? { ...current, services: current.services.map((row) => row.id === id ? { ...row, ...patch } : row) } : current)
  const updateLocalPackage = (id: string, patch: Partial<ServicePackage>) => setData((current) => current ? { ...current, packages: current.packages.map((row) => row.id === id ? { ...row, ...patch } : row) } : current)
  const updateLocalScheduling = (patch: Partial<SchedulingSettings>) => setData((current) => current ? { ...current, scheduling: { ...current.scheduling, ...patch } } : current)

  if (!data) return <p className="loading-line">{error || 'Loading settings…'}</p>
  return <>
    <section className="page-heading"><div><p className="eyebrow">Capacity configuration</p><h1>Studio settings</h1><p>Working hours and exceptions use the Europe/Riga timezone.</p></div>{saving && <LoaderCircle className="spin" />}</section>
    {error && <p className="error" role="alert">{error}</p>}
    <section className="settings-section"><h2>Work bays</h2><div className="setting-cards">{data.bays.map((bay) => <label className="setting-card" key={bay.id}><span><strong>{bay.name}</strong><small>{bay.code}</small></span><input type="checkbox" checked={bay.is_active} onChange={(event) => void run({ action: 'update_bay', id: bay.id, isActive: event.target.checked })} /></label>)}</div></section>
    <section className="settings-section"><h2>Scheduling rules</h2><div className="settings-inline"><label>Start interval (minutes)<input type="number" min="5" max="120" step="5" value={data.scheduling.start_interval_minutes} onChange={(event) => updateLocalScheduling({ start_interval_minutes: Number(event.target.value) })} /></label><label>Pending capacity hold (minutes)<input type="number" min="5" max="1440" step="5" value={data.scheduling.pending_hold_minutes} onChange={(event) => updateLocalScheduling({ pending_hold_minutes: Number(event.target.value) })} /></label><button className="table-action" onClick={() => void run({ action: 'update_scheduling', startIntervalMinutes: data.scheduling.start_interval_minutes, pendingHoldMinutes: data.scheduling.pending_hold_minutes })}><Save size={14} /> Save rules</button></div><p className="settings-help">Pending public reservations release their future capacity automatically after the configured hold.</p></section>
    <section className="settings-section"><h2>Service durations</h2><p className="settings-help">A reservation uses each selected service’s work time plus its buffer. Changes affect new calculations only; saved reservations retain snapshots.</p><div className="catalog-settings"><div className="catalog-settings__head"><span>Service</span><span>Work minutes</span><span>Buffer</span><span>Active</span><span /></div>{data.services.map((service) => <div className="catalog-settings__row" key={service.id}><span><strong>{service.name_en}</strong><small>{service.slug}</small></span><input aria-label={`${service.name_en} duration`} type="number" min="30" max="10080" step="30" value={service.base_duration_minutes} onChange={(event) => updateLocalService(service.id, { base_duration_minutes: Number(event.target.value) })} /><input aria-label={`${service.name_en} buffer`} type="number" min="0" max="1440" step="15" value={service.buffer_minutes} onChange={(event) => updateLocalService(service.id, { buffer_minutes: Number(event.target.value) })} /><input aria-label={`${service.name_en} active`} type="checkbox" checked={service.is_active} onChange={(event) => updateLocalService(service.id, { is_active: event.target.checked })} /><button className="table-action" onClick={() => void run({ action: 'update_service', id: service.id, baseDurationMinutes: service.base_duration_minutes, bufferMinutes: service.buffer_minutes, isActive: service.is_active })}><Save size={14} /> Save</button></div>)}</div></section>
    <section className="settings-section"><h2>Package durations</h2><p className="settings-help">A package uses its own configured work time and buffer; its service items are not added together.</p><div className="catalog-settings"><div className="catalog-settings__head"><span>Package</span><span>Work minutes</span><span>Buffer</span><span>Active</span><span /></div>{data.packages.map((item) => <div className="catalog-settings__row" key={item.id}><span><strong>{item.name_en}</strong><small>{item.code}</small></span><input aria-label={`${item.name_en} duration`} type="number" min="30" max="10080" step="30" value={item.base_duration_minutes} onChange={(event) => updateLocalPackage(item.id, { base_duration_minutes: Number(event.target.value) })} /><input aria-label={`${item.name_en} buffer`} type="number" min="0" max="1440" step="15" value={item.buffer_minutes} onChange={(event) => updateLocalPackage(item.id, { buffer_minutes: Number(event.target.value) })} /><input aria-label={`${item.name_en} active`} type="checkbox" checked={item.is_active} onChange={(event) => updateLocalPackage(item.id, { is_active: event.target.checked })} /><button className="table-action" onClick={() => void run({ action: 'update_package', id: item.id, baseDurationMinutes: item.base_duration_minutes, bufferMinutes: item.buffer_minutes, isActive: item.is_active })}><Save size={14} /> Save</button></div>)}</div></section>
    <section className="settings-section"><h2>Weekly working hours</h2><div className="hours-list">{data.businessHours.map((row) => <div className="hours-row" key={row.weekday}><strong>{days[row.weekday]}</strong><label><input type="checkbox" checked={row.is_closed} onChange={(event) => updateLocalHours(row.weekday, { is_closed: event.target.checked })} /> Closed</label><input type="time" disabled={row.is_closed} value={row.opens_at?.slice(0, 5) ?? '10:00'} onChange={(event) => updateLocalHours(row.weekday, { opens_at: event.target.value })} /><input type="time" disabled={row.is_closed} value={row.closes_at?.slice(0, 5) ?? '20:00'} onChange={(event) => updateLocalHours(row.weekday, { closes_at: event.target.value })} /><button className="table-action" onClick={() => void run({ action: 'update_hours', weekday: row.weekday, isClosed: row.is_closed, opensAt: row.opens_at?.slice(0, 5), closesAt: row.closes_at?.slice(0, 5) })}><Save size={14} /> Save</button></div>)}</div></section>
    <section className="settings-section"><h2>Holidays and special hours</h2><form className="exception-form" onSubmit={(event) => { event.preventDefault(); void run({ action: 'set_exception', exceptionDate, isClosed: exceptionClosed, opensAt: exceptionOpen, closesAt: exceptionClose, note }); setExceptionDate(''); setNote('') }}><label>Date<input type="date" required value={exceptionDate} onChange={(event) => setExceptionDate(event.target.value)} /></label><label><input type="checkbox" checked={exceptionClosed} onChange={(event) => setExceptionClosed(event.target.checked)} /> Closed all day</label><label>Opens<input type="time" disabled={exceptionClosed} value={exceptionOpen} onChange={(event) => setExceptionOpen(event.target.value)} /></label><label>Closes<input type="time" disabled={exceptionClosed} value={exceptionClose} onChange={(event) => setExceptionClose(event.target.value)} /></label><label>Note<input maxLength={300} value={note} onChange={(event) => setNote(event.target.value)} /></label><button className="primary"><Save size={15} /> Add exception</button></form><div className="exception-list">{data.exceptions.map((entry) => <div key={entry.exception_date}><strong>{entry.exception_date}</strong><span>{entry.is_closed ? 'Closed' : `${entry.opens_at?.slice(0, 5)}–${entry.closes_at?.slice(0, 5)}`}</span><small>{entry.note}</small><button className="icon-action" aria-label={`Delete ${entry.exception_date}`} onClick={() => void run({ action: 'delete_exception', exceptionDate: entry.exception_date })}><Trash2 size={15} /></button></div>)}</div></section>
  </>
}
